FRUITS = []
F1 = input ("enter fruit name : ")
FRUITS.append(F1)
F2 = input ("enter fruit name : ")
FRUITS.append(F2)
F3 = input ("enter fruit name : ")
FRUITS.append(F3)
F4 = input ("enter fruit name : ")
FRUITS.append(F4)
F5 = input ("enter fruit name : ")
FRUITS.append(F5)
F6 = input ("enter fruit name : ")
FRUITS.append(F6)
F7 = input ("enter fruit name : ")
FRUITS.append(F7)
